#!/usr/bin/env python3
"""Generate sitemap.xml and robots.txt for the GitHub Pages deployment.

Without a sitemap, ~490 pages are only discoverable by crawling from the home
page, and the deeper notes are several clicks down. The sitemap lists them all
directly and carries a lastmod taken from git, so re-crawls are targeted.

`<lastmod>` comes from the file's last commit date rather than the filesystem
mtime: a fresh clone (and CI) would otherwise stamp every page with the
checkout time and tell crawlers the whole site changed at once.

Run after adding or removing pages:
    python scripts/build_sitemap.py
"""
from __future__ import annotations

import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _site import ROOT, content_dirs  # noqa: E402

BASE = "https://kavinchan13.github.io/tech-notes/"

# Pages a search engine should not spend crawl budget on.
SKIP_NAMES = {"index.html"}          # only at nested levels; the root one is kept


def git_lastmod() -> dict[str, str]:
    """path -> YYYY-MM-DD of the commit that last touched it."""
    out = subprocess.run(
        ["git", "log", "--name-only", "--format=%x00%cI", "--diff-filter=AM"],
        capture_output=True, text=True, encoding="utf-8", errors="replace", cwd=ROOT,
    ).stdout
    dates: dict[str, str] = {}
    current = ""
    for line in out.splitlines():
        if line.startswith("\x00"):
            current = line[1:11]
        elif line.strip() and line not in dates:
            dates[line.strip()] = current
    return dates


def priority(rel: str) -> str:
    if rel == "index.html":
        return "1.0"
    if rel.endswith("_directory.html"):
        return "0.8"
    if rel.endswith("_study_path.html"):
        return "0.7"
    return "0.6"


def main() -> None:
    lastmod = git_lastmod()
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    pages = [ROOT / "index.html"]
    for d in content_dirs():
        for p in sorted((ROOT / d).rglob("*.html"), key=lambda x: x.as_posix()):
            rel = p.relative_to(ROOT).as_posix()
            if p.name in SKIP_NAMES:
                continue
            pages.append(p)

    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for p in pages:
        rel = p.relative_to(ROOT).as_posix()
        loc = BASE if rel == "index.html" else BASE + rel
        lines.append("  <url>")
        lines.append(f"    <loc>{escape(loc)}</loc>")
        lines.append(f"    <lastmod>{lastmod.get(rel, today)}</lastmod>")
        lines.append(f"    <priority>{priority(rel)}</priority>")
        lines.append("  </url>")
    lines.append("</urlset>")
    (ROOT / "sitemap.xml").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="")

    robots = f"""# Kavin Tech Notes — generated by scripts/build_sitemap.py
User-agent: *
Allow: /

Sitemap: {BASE}sitemap.xml
"""
    (ROOT / "robots.txt").write_text(robots, encoding="utf-8", newline="")

    print(f"sitemap.xml: {len(pages)} urls")
    print("robots.txt: written")


if __name__ == "__main__":
    main()
