#!/usr/bin/env python3
"""Build the full-text search index for the whole site, split for delivery.

Outputs:
  assets/search-index-lite.js      -> window.TN_SEARCH_LITE  = [ ... ]
                                      window.TN_SEARCH_TOPICS = [ ... ]
  assets/search-index/<topic>.js   -> window.TN_SEARCH_SHARD['<topic>'] = [ ... ]

Why a .js (not .json): pages must work by double-click (file://). Under
file:// a fetch() of a local .json is blocked by CORS, but a <script src>
that assigns a global loads fine. So we emit JS files that define globals.

Why split: the body text is 94% of the payload, and one monolithic file meant
every consumer paid for all of it. The 16 directory pages filter only the files
they link to, yet each pulled the whole 14.7 MB (5.9 MB gzipped) index to do it.
Now:

  * a directory page loads one shard — 22 KB to 2 MB instead of 14.7 MB;
  * the home page's Cmd+K loads the lite index first (titles + section headings
    + anchors, ~500 KB / 149 KB gzipped) so results appear immediately, then
    pulls the shards in the background to upgrade to full-text matching.

No page links any of these directly; they ship the ~2 KB
assets/search-index-loader.js instead. See .cursor/rules/search-index.mdc.

Each entry:
  {
    u: "bigdata/spark_internals.html",   # root-relative url, forward slashes
    t: "Spark 内核",                      # title (before the first separator)
    c: "大数据",                          # category (from folder)
    s: [                                  # sections, in document order
      { a: "",      h: "",          x: "intro plain text..." },  # preamble -> page top
      { a: "ch1",   h: "RDD 与惰性求值", x: "section plain text..." },
      ...
    ]
  }

Excluded from the index (not "notes"):
  - *_directory.html      (listing pages)
  - *_cards.html          (interview / flash-card pages, per product decision)
  - index.html            (home / template scaffolding at any level)

Run after adding or substantially editing note pages:
    python scripts/build_search_index.py
"""
from __future__ import annotations

import html as html_lib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LITE_OUT = ROOT / "assets" / "search-index-lite.js"
SHARD_DIR = ROOT / "assets" / "search-index"
HEADER = "/* AUTO-GENERATED by scripts/build_search_index.py — do not edit by hand. */\n"

# folder -> human category (aligns with the home page domains)
CATEGORY = {
    "algorithms": "算法与数据结构",
    "cpp": "现代 C++ / STL",
    "stl": "现代 C++ / STL",
    "system": "Linux 系统",
    "bigdata": "大数据",
    "architect": "系统架构",
    "interview": "面试",
    "management": "管理",
    "ai-native": "AI 工程",
    "ai-infra": "AI Infra",
    "embedded-realtime": "嵌入式 / 实时",
    "perf-debug": "性能 / 调试",
    "pm": "产品管理",
    "ai-templates": "AI 模板",
    "neural-networks": "神经网络",
    "reinforcement": "强化学习",
    "communication": "通信系统",
    "desktop-gui": "桌面 GUI / Qt",
    "robotics-comm": "机器人通信",
}

SCRIPT_RE = re.compile(r"<script\b[\s\S]*?</script>", re.I)
STYLE_RE = re.compile(r"<style\b[\s\S]*?</style>", re.I)
TAG_RE = re.compile(r"<[^>]+>")
WS_RE = re.compile(r"\s+")
TITLE_RE = re.compile(r"<title[^>]*>(.*?)</title>", re.I | re.S)
H1_RE = re.compile(r"<h1[^>]*>(.*?)</h1>", re.I | re.S)
# anchor points = section/heading tags that carry an id (matches TOC targets)
ANCHOR_RE = re.compile(r'<(?:section|h1|h2|h3|h4)\b[^>]*\bid="([^"]+)"[^>]*>', re.I)
HEADING_RE = re.compile(r"<h[1-4][^>]*>(.*?)</h[1-4]>", re.I | re.S)

TITLE_SEP_RE = re.compile(r"\s*[·|—\-]\s*")


def strip_text(fragment: str) -> str:
    txt = TAG_RE.sub(" ", fragment)
    txt = html_lib.unescape(txt)
    return WS_RE.sub(" ", txt).strip()


def first_heading(fragment: str) -> str:
    m = HEADING_RE.search(fragment)
    return strip_text(m.group(1)) if m else ""


def extract_title(html: str) -> str:
    m = TITLE_RE.search(html)
    raw = strip_text(m.group(1)) if m else ""
    if raw:
        return TITLE_SEP_RE.split(raw, 1)[0].strip()
    m = H1_RE.search(html)
    return strip_text(m.group(1)) if m else ""


def build_sections(body: str) -> list[dict]:
    """Split cleaned body HTML into sections by anchored section/headings."""
    anchors = list(ANCHOR_RE.finditer(body))
    sections: list[dict] = []
    if not anchors:
        x = strip_text(body)
        return [{"a": "", "h": "", "x": x}] if x else []

    pre = strip_text(body[: anchors[0].start()])
    if pre:
        sections.append({"a": "", "h": "", "x": pre})

    for i, m in enumerate(anchors):
        start = m.start()
        end = anchors[i + 1].start() if i + 1 < len(anchors) else len(body)
        chunk = body[start:end]
        x = strip_text(chunk)
        if not x:
            continue
        sections.append({"a": m.group(1), "h": first_heading(chunk), "x": x})
    return sections


def should_skip(path: Path) -> bool:
    name = path.name
    rel_parts = path.relative_to(ROOT).parts
    # skip hidden / ignored working dirs (e.g. .private staging, .cache, .git)
    if any(part.startswith(".") for part in rel_parts[:-1]):
        return True
    if "node_modules" in path.parts:
        return True
    # Root-level pages are shells, not notes (index.html, 404.html). They also
    # have no topic folder, so indexing them produced a stray shard named after
    # the fallback category — a non-ASCII "其他.js" URL for a 404 page.
    if len(rel_parts) == 1:
        return True
    return (
        name == "index.html"
        or name.endswith("_directory.html")
        or name.endswith("_cards.html")
    )


def lite_entry(e: dict) -> dict:
    """Same record shape minus the body text: anchored headings only.

    Keeping the shape identical is what lets the home page render lite results
    with the very same code path — it simply finds no body matches until the
    shards arrive.
    """
    return {
        "u": e["u"],
        "t": e["t"],
        "c": e["c"],
        "s": [{"a": s["a"], "h": s["h"]} for s in e["s"] if s["h"] or s["a"]],
    }


def main() -> None:
    entries: list[dict] = []
    dup_check: dict[str, str] = {}
    # Sort on the posix string, not the Path: comparing Path objects uses
    # case-insensitive ordering on Windows and case-sensitive ordering on
    # Linux, so a file like interview/STUDY_PATH.html lands in a different
    # slot on each and the generated file differs between a local run and CI.
    for path in sorted(ROOT.rglob("*.html"), key=lambda p: p.as_posix()):
        if should_skip(path):
            continue
        rel = path.relative_to(ROOT).as_posix()
        folder = rel.split("/", 1)[0] if "/" in rel else ""
        raw = path.read_text(encoding="utf-8", errors="ignore")
        body = STYLE_RE.sub(" ", SCRIPT_RE.sub(" ", raw))
        sections = build_sections(body)
        if not sections:
            continue
        entries.append(
            {
                "u": rel,
                "t": extract_title(raw) or rel,
                "c": CATEGORY.get(folder, folder or "其他"),
                "s": sections,
                "_d": folder or "其他",
            }
        )
        dup_check.setdefault(path.name, rel)

    import json

    def dump(obj) -> str:
        return json.dumps(obj, ensure_ascii=False, separators=(",", ":"))

    shards: dict[str, list[dict]] = {}
    for e in entries:
        shards.setdefault(e.pop("_d"), []).append(e)
    topics = sorted(shards)

    # Rewrite the shard directory from scratch: a topic folder that loses its
    # last indexed page must lose its shard too, or the loader keeps fetching a
    # stale file that no longer matches anything.
    SHARD_DIR.mkdir(parents=True, exist_ok=True)
    for old in SHARD_DIR.glob("*.js"):
        if old.stem not in shards:
            old.unlink()

    shard_bytes = 0
    for topic in topics:
        out = SHARD_DIR / f"{topic}.js"
        out.write_text(
            HEADER
            + "(window.TN_SEARCH_SHARD=window.TN_SEARCH_SHARD||{})"
            + f"[{dump(topic)}]=" + dump(shards[topic]) + ";\n",
            encoding="utf-8",
            newline="\n",
        )
        shard_bytes += out.stat().st_size

    LITE_OUT.write_text(
        HEADER
        + "window.TN_SEARCH_TOPICS=" + dump(topics) + ";\n"
        + "window.TN_SEARCH_LITE=" + dump([lite_entry(e) for e in entries]) + ";\n",
        encoding="utf-8",
        newline="\n",
    )

    n_sec = sum(len(e["s"]) for e in entries)
    print(f"Indexed {len(entries)} pages, {n_sec} sections, {len(topics)} topics.")
    print(f"Wrote {LITE_OUT.relative_to(ROOT)} ({LITE_OUT.stat().st_size / 1024:.0f} KB)")
    print(f"Wrote {len(topics)} shards under {SHARD_DIR.relative_to(ROOT)}/ "
          f"({shard_bytes / 1024:.0f} KB total, "
          f"largest {max(f.stat().st_size for f in SHARD_DIR.glob('*.js')) / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
