#!/usr/bin/env python3
"""Build a full-text search index for the whole site.

Output: assets/search-index.js  ->  window.TN_SEARCH_INDEX = [ ... ]

Why a .js (not .json): pages must work by double-click (file://). Under
file:// a fetch() of a local .json is blocked by CORS, but a <script src>
that assigns a global loads fine. So we emit a JS file that defines a global.

Each entry:
  {
    u: "bigdata/spark_internals.html",   # root-relative url, forward slashes
    t: "Spark 内核",                      # title (before the first separator)
    c: "大数据",                          # category (from folder)
    s: [                                  # sections, in document order
      { a: "",      h: "",          x: "intro plain text..." },  # preamble -> page top
      { a: "ch1",   h: "RDD 与惰性求值", x: "section plain text..." },
      ...
    ]
  }

Excluded from the index (not "notes"):
  - *_directory.html      (listing pages)
  - *_cards.html          (interview / flash-card pages, per product decision)
  - index.html            (home / template scaffolding at any level)

Run after adding or substantially editing note pages:
    python scripts/build_search_index.py
"""
from __future__ import annotations

import html as html_lib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "search-index.js"

# folder -> human category (aligns with the home page domains)
CATEGORY = {
    "cpp": "现代 C++ / STL",
    "stl": "现代 C++ / STL",
    "system": "Linux 系统",
    "bigdata": "大数据",
    "architect": "系统架构",
    "interview": "面试",
    "management": "管理",
    "ai-native": "AI 工程",
    "ai-infra": "AI Infra",
    "embedded-realtime": "嵌入式 / 实时",
    "perf-debug": "性能 / 调试",
    "pm": "产品管理",
    "ai-templates": "AI 模板",
}

SCRIPT_RE = re.compile(r"<script\b[\s\S]*?</script>", re.I)
STYLE_RE = re.compile(r"<style\b[\s\S]*?</style>", re.I)
TAG_RE = re.compile(r"<[^>]+>")
WS_RE = re.compile(r"\s+")
TITLE_RE = re.compile(r"<title[^>]*>(.*?)</title>", re.I | re.S)
H1_RE = re.compile(r"<h1[^>]*>(.*?)</h1>", re.I | re.S)
# anchor points = section/heading tags that carry an id (matches TOC targets)
ANCHOR_RE = re.compile(r'<(?:section|h1|h2|h3|h4)\b[^>]*\bid="([^"]+)"[^>]*>', re.I)
HEADING_RE = re.compile(r"<h[1-4][^>]*>(.*?)</h[1-4]>", re.I | re.S)

TITLE_SEP_RE = re.compile(r"\s*[·|—\-]\s*")


def strip_text(fragment: str) -> str:
    txt = TAG_RE.sub(" ", fragment)
    txt = html_lib.unescape(txt)
    return WS_RE.sub(" ", txt).strip()


def first_heading(fragment: str) -> str:
    m = HEADING_RE.search(fragment)
    return strip_text(m.group(1)) if m else ""


def extract_title(html: str) -> str:
    m = TITLE_RE.search(html)
    raw = strip_text(m.group(1)) if m else ""
    if raw:
        return TITLE_SEP_RE.split(raw, 1)[0].strip()
    m = H1_RE.search(html)
    return strip_text(m.group(1)) if m else ""


def build_sections(body: str) -> list[dict]:
    """Split cleaned body HTML into sections by anchored section/headings."""
    anchors = list(ANCHOR_RE.finditer(body))
    sections: list[dict] = []
    if not anchors:
        x = strip_text(body)
        return [{"a": "", "h": "", "x": x}] if x else []

    pre = strip_text(body[: anchors[0].start()])
    if pre:
        sections.append({"a": "", "h": "", "x": pre})

    for i, m in enumerate(anchors):
        start = m.start()
        end = anchors[i + 1].start() if i + 1 < len(anchors) else len(body)
        chunk = body[start:end]
        x = strip_text(chunk)
        if not x:
            continue
        sections.append({"a": m.group(1), "h": first_heading(chunk), "x": x})
    return sections


def should_skip(path: Path) -> bool:
    name = path.name
    return (
        name == "index.html"
        or name.endswith("_directory.html")
        or name.endswith("_cards.html")
    )


def main() -> None:
    entries: list[dict] = []
    dup_check: dict[str, str] = {}
    for path in sorted(ROOT.rglob("*.html")):
        if should_skip(path):
            continue
        rel = path.relative_to(ROOT).as_posix()
        folder = rel.split("/", 1)[0] if "/" in rel else ""
        raw = path.read_text(encoding="utf-8", errors="ignore")
        body = STYLE_RE.sub(" ", SCRIPT_RE.sub(" ", raw))
        sections = build_sections(body)
        if not sections:
            continue
        entries.append(
            {
                "u": rel,
                "t": extract_title(raw) or rel,
                "c": CATEGORY.get(folder, folder or "其他"),
                "s": sections,
            }
        )
        dup_check.setdefault(path.name, rel)

    import json

    payload = json.dumps(entries, ensure_ascii=False, separators=(",", ":"))
    OUT.write_text(
        "/* AUTO-GENERATED by scripts/build_search_index.py — do not edit by hand. */\n"
        "window.TN_SEARCH_INDEX=" + payload + ";\n",
        encoding="utf-8",
    )

    size_kb = OUT.stat().st_size / 1024
    n_sec = sum(len(e["s"]) for e in entries)
    print(f"Indexed {len(entries)} pages, {n_sec} sections.")
    print(f"Wrote {OUT.relative_to(ROOT)} ({size_kb:.0f} KB)")


if __name__ == "__main__":
    main()
