#!/usr/bin/env python3
"""Generate sitemap.xml and robots.txt for the GitHub Pages deployment.

Without a sitemap, ~490 pages are only discoverable by crawling from the home
page, and the deeper notes are several clicks down. The sitemap lists them all
directly and carries a lastmod taken from git, so re-crawls are targeted.

`<lastmod>` comes from the file's last commit date rather than the filesystem
mtime: a fresh clone (and CI) would otherwise stamp every page with the
checkout time and tell crawlers the whole site changed at once.

Run after adding or removing pages:
    python scripts/build_sitemap.py
    python scripts/build_sitemap.py --check   # CI: is the URL set current?

`--check` compares only the set of <loc> values, never <lastmod>. Committing
the sitemap is itself a commit, so every page touched by that commit gets a new
last-commit date the moment it lands — a byte-for-byte gate could never be
satisfied. The URL set is the part that actually goes stale (a page added or
removed without regenerating), so that is what CI enforces.
"""
from __future__ import annotations

import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _site import ROOT, content_dirs  # noqa: E402

BASE = "https://kavinchan13.github.io/tech-notes/"

# Pages a search engine should not spend crawl budget on.
SKIP_NAMES = {"index.html"}          # only at nested levels; the root one is kept


def git_lastmod() -> dict[str, str]:
    """path -> YYYY-MM-DD of the commit that last touched it."""
    out = subprocess.run(
        ["git", "log", "--name-only", "--format=%x00%cI", "--diff-filter=AM"],
        capture_output=True, text=True, encoding="utf-8", errors="replace", cwd=ROOT,
    ).stdout
    dates: dict[str, str] = {}
    current = ""
    for line in out.splitlines():
        if line.startswith("\x00"):
            current = line[1:11]
        elif line.strip() and line not in dates:
            dates[line.strip()] = current
    return dates


def priority(rel: str) -> str:
    if rel == "index.html":
        return "1.0"
    if rel.endswith("_directory.html"):
        return "0.8"
    if rel.endswith("_study_path.html"):
        return "0.7"
    return "0.6"


def main(argv: list[str] | None = None) -> int:
    check = "--check" in (argv or [])
    lastmod = git_lastmod()
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    pages = [ROOT / "index.html"]
    for d in content_dirs():
        for p in sorted((ROOT / d).rglob("*.html"), key=lambda x: x.as_posix()):
            rel = p.relative_to(ROOT).as_posix()
            if p.name in SKIP_NAMES:
                continue
            pages.append(p)

    locs = []
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for p in pages:
        rel = p.relative_to(ROOT).as_posix()
        loc = BASE if rel == "index.html" else BASE + rel
        locs.append(loc)
        lines.append("  <url>")
        lines.append(f"    <loc>{escape(loc)}</loc>")
        lines.append(f"    <lastmod>{lastmod.get(rel, today)}</lastmod>")
        lines.append(f"    <priority>{priority(rel)}</priority>")
        lines.append("  </url>")
    lines.append("</urlset>")

    out = ROOT / "sitemap.xml"
    if check:
        if not out.exists():
            print("sitemap.xml is missing — run python scripts/build_sitemap.py")
            return 1
        have = set(re.findall(r"<loc>([^<]+)</loc>", out.read_text(encoding="utf-8")))
        want = set(locs)
        missing, extra = sorted(want - have), sorted(have - want)
        for m in missing:
            print(f"  missing from sitemap.xml: {m}")
        for e in extra:
            print(f"  stale entry in sitemap.xml: {e}")
        if missing or extra:
            print(f"\nsitemap.xml is out of date ({len(missing)} missing, {len(extra)} stale)")
            return 1
        print(f"sitemap.xml is current: {len(want)} urls")
        return 0

    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="")

    robots = f"""# Kavin Tech Notes — generated by scripts/build_sitemap.py
User-agent: *
Allow: /

Sitemap: {BASE}sitemap.xml
"""
    (ROOT / "robots.txt").write_text(robots, encoding="utf-8", newline="")

    print(f"sitemap.xml: {len(pages)} urls")
    print("robots.txt: written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
